# Package Overview
package_name: genre_model

pipeline_name: genre_model
pipeline_save_file: genre_model_output_v

# Data Files
training_data_file: features_3_sec.csv
test_data_file: test.csv

le_save_file: le.pkl

# Variables
# The variable we are attempting to predict
target: label

features:
  - chroma_stft_mean
  - chroma_stft_var
  - rms_mean
  - rms_var
  - spectral_centroid_mean
  - spectral_centroid_var
  - spectral_bandwidth_mean
  - spectral_bandwidth_var
  - rolloff_mean
  - rolloff_var
  - zero_crossing_rate_mean
  - zero_crossing_rate_var
  - harmony_mean
  - harmony_var
  - tempo
  - mfcc1_mean
  - mfcc1_var
  - mfcc2_mean
  - mfcc2_var
  - mfcc3_mean
  - mfcc3_var
  - mfcc4_mean
  - mfcc4_var
  - mfcc5_mean
  - mfcc5_var
  - mfcc6_mean
  - mfcc6_var
  - mfcc7_mean
  - mfcc7_var
  - mfcc8_mean
  - mfcc8_var
  - mfcc9_mean
  - mfcc9_var
  - mfcc10_mean
  - mfcc10_var
  - mfcc11_mean
  - mfcc11_var
  - mfcc12_mean
  - mfcc12_var
  - mfcc13_mean
  - mfcc13_var
  - mfcc14_mean
  - mfcc14_var
  - mfcc15_mean
  - mfcc15_var
  - mfcc16_mean
  - mfcc16_var
  - mfcc17_mean
  - mfcc17_var
  - mfcc18_mean
  - mfcc18_var
  - mfcc19_mean
  - mfcc19_var
  - mfcc20_mean
  - mfcc20_var

variables_to_drop:
  - filename
  - perceptr_var
  - perceptr_mean
  - length

categorical_vars:
  - label

numerical_vars:
  - chroma_stft_mean
  - chroma_stft_var
  - rms_mean
  - rms_var
  - spectral_centroid_mean
  - spectral_centroid_var
  - spectral_bandwidth_mean
  - spectral_bandwidth_var
  - rolloff_mean
  - rolloff_var
  - zero_crossing_rate_mean
  - zero_crossing_rate_var
  - harmony_mean
  - harmony_var
  - tempo
  - mfcc1_mean
  - mfcc1_var
  - mfcc2_mean
  - mfcc2_var
  - mfcc3_mean
  - mfcc3_var
  - mfcc4_mean
  - mfcc4_var
  - mfcc5_mean
  - mfcc5_var
  - mfcc6_mean
  - mfcc6_var
  - mfcc7_mean
  - mfcc7_var
  - mfcc8_mean
  - mfcc8_var
  - mfcc9_mean
  - mfcc9_var
  - mfcc10_mean
  - mfcc10_var
  - mfcc11_mean
  - mfcc11_var
  - mfcc12_mean
  - mfcc12_var
  - mfcc13_mean
  - mfcc13_var
  - mfcc14_mean
  - mfcc14_var
  - mfcc15_mean
  - mfcc15_var
  - mfcc16_mean
  - mfcc16_var
  - mfcc17_mean
  - mfcc17_var
  - mfcc18_mean
  - mfcc18_var
  - mfcc19_mean
  - mfcc19_var
  - mfcc20_mean
  - mfcc20_var


# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

